#!/usr/bin/env node
// Builds the engine (docs/engine.md §1.6).
//
//   node engine/tools/build.mjs wasm-release      → src/renderer/src/engine/wasm/engine.{mjs,wasm}
//   node engine/tools/build.mjs wasm-debug        → the same with assertions and engine.wasm.map
//   node engine/tools/build.mjs native-test --test → builds and runs the doctest suite (ASan/UBSan)
//
// It finds emsdk ($EMSDK or ~/emsdk) and sets EMSDK, EM_CONFIG and PATH itself
// (no emsdk_env.sh), puts cmake/ninja on PATH from ~/Library/Python/3.9/bin
// when missing, and picks a Python ≥ 3.10 for emcc (EMSDK_PYTHON, else `uv
// python find 3.12`, else python3).
import { spawnSync } from "node:child_process";
import console from "node:console";
import { copyFileSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const engineDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const repo = path.resolve(engineDir, "..");
const outDir = path.join(repo, "src/renderer/src/engine/wasm");
const preset = process.argv[2] ?? "wasm-release";
const runTests = process.argv.includes("--test");
const extra = process.argv.slice(3).filter((a) => a !== "--test");
const presets = ["wasm-release", "wasm-debug", "native-test"];
if (!presets.includes(preset)) fail(`unknown preset "${preset}" (one of ${presets.join(", ")})`);
const wasm = preset.startsWith("wasm");

function fail(message) {
  console.error(`engine: ${message}`);
  process.exit(1);
}

function onPath(cmd, env) {
  return spawnSync("sh", ["-c", `command -v ${cmd}`], { env, encoding: "utf8" }).status === 0;
}

function run(cmd, args, env, cwd = engineDir) {
  const r = spawnSync(cmd, args, { cwd, env, stdio: "inherit" });
  if (r.error) fail(`${cmd}: ${r.error.message}`);
  if (r.status !== 0) process.exit(r.status ?? 1);
}

const env = { ...process.env };
const toolsBin = path.join(homedir(), "Library/Python/3.9/bin");
if ((!onPath("cmake", env) || !onPath("ninja", env)) && existsSync(toolsBin)) env.PATH = `${toolsBin}:${env.PATH}`;
if (!onPath("cmake", env) || !onPath("ninja", env)) fail("cmake and ninja are needed (pip install --user cmake ninja)");

if (wasm) {
  const emsdk = env.EMSDK && existsSync(env.EMSDK) ? env.EMSDK : path.join(homedir(), "emsdk");
  const emscripten = path.join(emsdk, "upstream/emscripten");
  if (!existsSync(path.join(emscripten, "emcc"))) fail(`Emscripten not found in ${emsdk} (set EMSDK)`);
  env.EMSDK = emsdk;
  env.EM_CONFIG = env.EM_CONFIG ?? path.join(emsdk, ".emscripten");
  env.PATH = `${emsdk}:${emscripten}:${env.PATH}`;
  if (!env.EMSDK_PYTHON) {
    const uv = path.join(toolsBin, "uv");
    const found = existsSync(uv) ? spawnSync(uv, ["python", "find", "3.12"], { encoding: "utf8" }) : null;
    if (found?.status === 0 && found.stdout.trim()) env.EMSDK_PYTHON = found.stdout.trim();
  }
  const pinned = readFileSync(path.join(engineDir, "EMSDK_VERSION"), "utf8").trim();
  const versionFile = path.join(emscripten, "emscripten-version.txt");
  const active = existsSync(versionFile) ? readFileSync(versionFile, "utf8").trim().replace(/"/g, "") : "?";
  if (active !== pinned) console.warn(`engine: Emscripten ${active} is active, engine/EMSDK_VERSION pins ${pinned}`);
}

const buildDir = path.join(engineDir, "build", preset);
if (!existsSync(path.join(buildDir, "CMakeCache.txt"))) run("cmake", ["--preset", preset], env);
run("cmake", ["--build", "--preset", preset, ...(wasm ? ["--target", "engine_wasm"] : [])], env);

if (wasm) {
  mkdirSync(outDir, { recursive: true });
  // The glue, marked as generated (lint skips src/renderer/src/engine/wasm/).
  const glue = readFileSync(path.join(buildDir, "engine.mjs"), "utf8");
  writeFileSync(path.join(outDir, "engine.mjs"), `// Generated by Emscripten (engine/tools/build.mjs ${preset}). Do not edit.\n${glue}`);
  copyFileSync(path.join(buildDir, "engine.wasm"), path.join(outDir, "engine.wasm"));
  const map = path.join(buildDir, "engine.wasm.map");
  if (preset === "wasm-debug" && existsSync(map)) copyFileSync(map, path.join(outDir, "engine.wasm.map"));
  else rmSync(path.join(outDir, "engine.wasm.map"), { force: true });
  const kb = (f) => `${Math.round(readFileSync(path.join(outDir, f)).length / 1024)} KB`;
  console.log(`engine: ${preset} → src/renderer/src/engine/wasm/ (engine.mjs ${kb("engine.mjs")}, engine.wasm ${kb("engine.wasm")})`);
}

if (runTests) {
  if (preset !== "native-test") fail("--test runs the native-test preset");
  // The vendored libraries are built without the sanitizers: libc++'s container annotations then disagree between a
  // template instantiated in an instrumented and an uninstrumented TU (a known ASan false positive, "container-overflow"
  // in Clipper2's priority_queue). Everything else ASan checks stays on.
  env.ASAN_OPTIONS = env.ASAN_OPTIONS ?? "detect_container_overflow=0";
  run(path.join(buildDir, "engine_tests"), extra, env);
}
