#!/usr/bin/env python3
"""Generates engine/src/text/CaseMap.generated.h: Unicode's simple (one code point
to one code point) upper, lower and title case mappings as delta ranges, from
Python's own Unicode database (str.upper/lower/title, single-character results
only; U+0130 İ lowercases to i as UnicodeData.txt's simple mapping says).

    python3 engine/tools/gen-casemap.py      (Python ≥ 3.12 for Unicode 15)
"""
import os
import sys
import unicodedata


def mapping(fn, special):
    out = {}
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        if cp in special:
            m = special[cp]
        else:
            r = fn(c)
            if len(r) != 1:
                continue
            m = ord(r)
        if m != cp:
            out[cp] = m
    return out


def ranges(m):
    """Runs of code points (stride 1 or 2) sharing one delta."""
    keys = sorted(m)
    out = []
    i = 0
    while i < len(keys):
        start = keys[i]
        delta = m[start] - start
        stride = 1
        j = i
        if i + 1 < len(keys) and m[keys[i + 1]] - keys[i + 1] == delta and keys[i + 1] - start in (1, 2):
            stride = keys[i + 1] - start
        end = start
        while j + 1 < len(keys) and keys[j + 1] == end + stride and m[keys[j + 1]] - keys[j + 1] == delta:
            j += 1
            end = keys[j]
        out.append((start, end, delta, stride))
        i = j + 1
    return out


def emit(name, rs):
    lines = [f"inline constexpr CaseRange {name}[] = {{"]
    row = []
    for r in rs:
        row.append("{0x%X, 0x%X, %d, %d}" % r)
        if len(row) == 4:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ", ".join(row) + ",")
    lines.append("};")
    return "\n".join(lines)


upper = ranges(mapping(str.upper, {}))
lower = ranges(mapping(str.lower, {0x130: 0x69}))
title = ranges(mapping(str.title, {}))
body = f"""// Generated by engine/tools/gen-casemap.py (Unicode {unicodedata.unidata_version}). Do not edit.
// Simple case mappings as ranges: code points start..end (every `stride`-th) map to cp + delta.
#pragma once

#include <cstdint>

namespace eng::text {{

struct CaseRange {{
  uint32_t start, end;
  int32_t delta;
  uint32_t stride;
}};

{emit("kUpper", upper)}

{emit("kLower", lower)}

{emit("kTitle", title)}

}}  // namespace eng::text
"""
path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "text", "CaseMap.generated.h")
open(path, "w").write(body)
print(f"casemap: Unicode {unicodedata.unidata_version}, {len(upper)}/{len(lower)}/{len(title)} ranges", file=sys.stderr)
