/* global process, console */
// node shaderpresets.mjs <presets.json> <out.h>: the renderer's table of Figma's shader presets (render/ShaderPaint.cpp)
// from src/shared/shaders/presets.json, the one definition the panels read too. Run by CMake (cmake/Generators.cmake)
// into <build>/generated/render/shader_presets.h; never committed.
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname } from "node:path";

const [input, output] = process.argv.slice(2);
if (!input || !output) {
  console.error("usage: node shaderpresets.mjs <presets.json> <out.h>");
  process.exit(2);
}
const src = JSON.parse(readFileSync(input, "utf8"));
const TYPES = { number: "Number", color: "Color", choice: "Choice", toggle: "Toggle" };
const MAX_PARAMS = 12;

const num = (v) => {
  const s = Number(v).toPrecision(9).replace(/\.?0+$/, "").replace(/\.?0+e/, "e");
  return /[.e]/.test(s) ? `${s}f` : `${s}.f`;
};
const hex = (h) => {
  const m = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i.exec(h);
  if (!m) throw new Error(`bad colour ${h}`);
  const n = parseInt(m[1], 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255, m[2] ? parseInt(m[2], 16) : 255].map((c) => c / 255);
};

const rows = [];
const add = (p, effect, program) => {
  if (p.params.length > MAX_PARAMS) throw new Error(`${p.key}: more than ${MAX_PARAMS} parameters`);
  const colors = p.params.filter((q) => q.type === "color").length;
  if (colors > 6 || p.params.length - colors > 24) throw new Error(`${p.key}: too many colours or values for the uniform slots`);
  const params = p.params.map((q) => {
    const type = TYPES[q.type];
    if (!type) throw new Error(`${p.key}: unknown type ${q.type}`);
    const v = q.type === "color" ? hex(q.default) : [q.type === "toggle" ? (q.default ? 1 : 0) : Number(q.default), 0, 0, 0];
    return `{${q.id}, ParamType::${type}, {${v.map(num).join(", ")}}}`;
  });
  rows.push(`    {${JSON.stringify(p.key)}, ${JSON.stringify(p.name)}, ${effect}, ${program}, ${p.params.length}, {${params.join(", ")}}},`);
};
src.fills.forEach((p, i) => add(p, false, i));
src.effects.forEach((p, i) => add(p, true, i));

const out = `// GENERATED by engine/tools/shaderpresets.mjs from src/shared/shaders/presets.json — do not edit.
#pragma once

#include <cstdint>

namespace eng::shaders {

enum class ParamType : uint8_t { Number = 0, Color = 1, Choice = 2, Toggle = 3 };
// A parameter: its defID's localID (sessionID 0), its type, its default (a colour: r g b a, straight; else .x).
struct ParamDef {
  uint32_t id;
  ParamType type;
  float value[4];
};
// A preset: its key (customEffectId.assetRef.key), name, an effect (else a fill), its program in the shader's switch.
struct PresetDef {
  const char* key;
  const char* name;
  bool effect;
  uint8_t program;
  uint8_t count;
  ParamDef params[${MAX_PARAMS}];
};

inline constexpr PresetDef kPresets[] = {
${rows.join("\n")}
};
inline constexpr int kPresetCount = ${rows.length};
inline constexpr int kFillPresets = ${src.fills.length};
inline constexpr int kEffectPresets = ${src.effects.length};

}  // namespace eng::shaders
`;
if (!existsSync(output) || readFileSync(output, "utf8") !== out) {
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, out);
}
