/**
 * The MCP server's stdio entry, for clients that start a command instead of calling a URL (and for any client
 * once the app's port changed): a small script, written next to the app's agent settings at every start, that the
 * app's own binary runs as Node (`ELECTRON_RUN_AS_NODE=1 <app> designer-mcp.cjs`). It reads the running server's URL
 * and token from `server.json` (mode 0600, rewritten when the server starts) and relays each JSON-RPC line from
 * stdin to it, its answers to stdout — so the client's config holds no token at all.
 */
export const STDIO_BRIDGE_SOURCE = String.raw`#!/usr/bin/env node
// DesignerV2's MCP server over stdio (generated by the app; it is rewritten at every start).
"use strict";
const fs = require("fs");
const path = require("path");
const http = require("http");
const readline = require("readline");
const discovery = process.argv[2] || path.join(__dirname, "server.json");
let session = null;
function server() {
  try {
    return JSON.parse(fs.readFileSync(discovery, "utf8"));
  } catch {
    return null;
  }
}
function reply(id, code, message) {
  if (id === undefined) return;
  process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id, error: { code, message } }) + "\n");
}
function post(line) {
  let msg;
  try {
    msg = JSON.parse(line);
  } catch {
    return reply(null, -32700, "Parse error");
  }
  const s = server();
  if (!s || !s.url) return reply(msg.id, -32000, "DesignerV2 isn't running: open the app and try again.");
  const u = new URL(s.url);
  const body = Buffer.from(JSON.stringify(msg));
  const headers = { "Content-Type": "application/json", Accept: "application/json, text/event-stream", Authorization: "Bearer " + s.token, "Content-Length": body.length };
  if (session) headers["Mcp-Session-Id"] = session;
  const req = http.request({ host: u.hostname, port: u.port, path: u.pathname, method: "POST", headers }, (res) => {
    const sid = res.headers["mcp-session-id"];
    if (typeof sid === "string") session = sid;
    const chunks = [];
    res.on("data", (c) => chunks.push(c));
    res.on("end", () => {
      const text = Buffer.concat(chunks).toString("utf8").trim();
      if (res.statusCode === 404 && session) {
        session = null;
        return post(line);
      }
      if (text) process.stdout.write(text + "\n");
    });
  });
  req.on("error", (e) => reply(msg.id, -32000, "DesignerV2 isn't reachable: " + e.message));
  req.end(body);
}
readline.createInterface({ input: process.stdin }).on("line", (l) => l.trim() && post(l));
`;
