// GENERATED by engine/tools/schemagen from engine/tools/schemagen/fieldmeta.ts. Do not edit: run `npm run engine:gen`.
/**
 * The typed per-facet reads (engine_read_facets; docs/engine.md §2.3): each facet's record layout and its decoder into
 * the field shapes engine_read_nodes gives (enum names, {x, y}, {m00 … m12}, {value, units}) — Figma's generated
 * per-facet bindings (*FacetTsApiGenerated) in this engine's flat-ABI form.
 */

export type FacetName = "geometry" | "shape" | "stack" | "stroke" | "text";

/** Each facet's bit in engine_read_facets' mask is 1 << id. */
export const FACET_IDS: Readonly<Record<FacetName, number>> = { geometry: 0, shape: 1, stack: 2, stroke: 3, text: 4 };
/** Each facet's record length in f64 slots. */
export const FACET_SLOTS: Readonly<Record<FacetName, number>> = { geometry: 24, shape: 5, stack: 19, stroke: 14, text: 15 };
/** The fields (schema NodeChange names) each facet carries. */
export const FACET_FIELDS: Readonly<Record<FacetName, readonly string[]>> = {
  geometry: ["type", "visible", "locked", "opacity", "transform", "size", "cornerRadius", "rectangleCornerRadiiIndependent", "rectangleTopLeftCornerRadius", "rectangleTopRightCornerRadius", "rectangleBottomRightCornerRadius", "rectangleBottomLeftCornerRadius", "horizontalConstraint", "verticalConstraint", "proportionsConstrained", "stackChildPrimaryGrow", "stackChildAlignSelf", "stackPositioning"],
  shape: ["arcData", "count", "starInnerScale"],
  stack: ["stackMode", "stackSpacing", "stackCounterSpacing", "stackHorizontalPadding", "stackVerticalPadding", "stackPaddingRight", "stackPaddingBottom", "stackPrimarySizing", "stackCounterSizing", "stackPrimaryAlignItems", "stackCounterAlignItems", "stackCounterAlignContent", "stackWrap", "stackReverseZIndex", "bordersTakeSpace", "minSize", "maxSize"],
  stroke: ["strokeWeight", "strokeAlign", "strokeCap", "strokeJoin", "miterLimit", "borderTopWeight", "borderRightWeight", "borderBottomWeight", "borderLeftWeight", "borderStrokeWeightsIndependent", "cornerSmoothing", "blendMode", "mask", "frameMaskDisabled"],
  text: ["fontSize", "lineHeight", "letterSpacing", "paragraphSpacing", "paragraphIndent", "textAlignHorizontal", "textAlignVertical", "textAutoResize", "textTruncation", "maxLines", "textCase", "textDecoration", "autoRename"],
};

const BlendMode = ["PASS_THROUGH","NORMAL","DARKEN","MULTIPLY","LINEAR_BURN","COLOR_BURN","LIGHTEN","SCREEN","LINEAR_DODGE","COLOR_DODGE","OVERLAY","SOFT_LIGHT","HARD_LIGHT","DIFFERENCE","EXCLUSION","HUE","SATURATION","COLOR","LUMINOSITY"] as const;
const ConstraintType = ["MIN","CENTER","MAX","STRETCH","SCALE","FIXED_MIN","FIXED_MAX"] as const;
const NodeType = ["NONE","DOCUMENT","CANVAS","GROUP","FRAME","BOOLEAN_OPERATION","VECTOR","STAR","LINE","ELLIPSE","RECTANGLE","REGULAR_POLYGON","ROUNDED_RECTANGLE","TEXT","SLICE","SYMBOL","INSTANCE","","","","","","","","","SECTION","","","VARIABLE","","","VARIABLE_SET","","","","VARIABLE_OVERRIDE","","","","","","","","","","","BRUSH"] as const;
const NumberUnits = ["RAW","PIXELS","PERCENT"] as const;
const StackAlign = ["MIN","CENTER","MAX","BASELINE"] as const;
const StackCounterAlign = ["MIN","CENTER","MAX","STRETCH","AUTO","BASELINE"] as const;
const StackCounterAlignContent = ["AUTO","SPACE_BETWEEN"] as const;
const StackJustify = ["MIN","CENTER","MAX","SPACE_EVENLY","SPACE_BETWEEN","SPACE_AROUND","SPACE_EVENLY_CSS"] as const;
const StackMode = ["NONE","HORIZONTAL","VERTICAL","GRID"] as const;
const StackPositioning = ["AUTO","ABSOLUTE"] as const;
const StackSize = ["FIXED","RESIZE_TO_FIT","RESIZE_TO_FIT_WITH_IMPLICIT_SIZE"] as const;
const StackWrap = ["NO_WRAP","WRAP"] as const;
const StrokeAlign = ["CENTER","INSIDE","OUTSIDE"] as const;
const StrokeCap = ["NONE","ROUND","SQUARE","ARROW_LINES","ARROW_EQUILATERAL","DIAMOND_FILLED","TRIANGLE_FILLED","","","","","","","","CIRCLE_FILLED"] as const;
const StrokeJoin = ["MITER","BEVEL","ROUND"] as const;
const TextAlignHorizontal = ["LEFT","CENTER","RIGHT","JUSTIFIED"] as const;
const TextAlignVertical = ["TOP","CENTER","BOTTOM"] as const;
const TextAutoResize = ["NONE","WIDTH_AND_HEIGHT","HEIGHT"] as const;
const TextCase = ["ORIGINAL","UPPER","LOWER","TITLE","SMALL_CAPS","SMALL_CAPS_FORCED"] as const;
const TextDecoration = ["NONE","UNDERLINE","STRIKETHROUGH"] as const;
const TextTruncation = ["DISABLED","ENDING"] as const;

/** Place, size, kind, corners, constraints, auto-layout child (core fields) */
export interface GeometryFacet {
  type: string;
  visible: boolean;
  locked: boolean;
  opacity: number;
  transform: { m00: number; m01: number; m02: number; m10: number; m11: number; m12: number };
  size: { x: number; y: number };
  cornerRadius: number;
  rectangleCornerRadiiIndependent: boolean;
  rectangleTopLeftCornerRadius: number;
  rectangleTopRightCornerRadius: number;
  rectangleBottomRightCornerRadius: number;
  rectangleBottomLeftCornerRadius: number;
  horizontalConstraint: string;
  verticalConstraint: string;
  proportionsConstrained: boolean;
  stackChildPrimaryGrow: number;
  stackChildAlignSelf: string;
  stackPositioning: string;
}

/** Arc, point count, star ratio (ShapeFacet) */
export interface ShapeFacet {
  arcData: { startingAngle: number; endingAngle: number; innerRadius: number };
  count: number;
  starInnerScale: number;
}

/** Auto layout container fields and min / max sizes (StackFacet, RareFacet) */
export interface StackFacet {
  stackMode: string;
  stackSpacing: number;
  stackCounterSpacing?: number;
  stackHorizontalPadding: number;
  stackVerticalPadding: number;
  stackPaddingRight: number;
  stackPaddingBottom: number;
  stackPrimarySizing: string;
  stackCounterSizing: string;
  stackPrimaryAlignItems: string;
  stackCounterAlignItems: string;
  stackCounterAlignContent: string;
  stackWrap: string;
  stackReverseZIndex: boolean;
  bordersTakeSpace: boolean;
  minSize: { value: { x: number; y: number } };
  maxSize: { value: { x: number; y: number } };
}

/** Stroke weight, align, caps, joins, per-side weights, corner smoothing */
export interface StrokeFacet {
  strokeWeight: number;
  strokeAlign: string;
  strokeCap: string;
  strokeJoin: string;
  miterLimit: number;
  borderTopWeight: number;
  borderRightWeight: number;
  borderBottomWeight: number;
  borderLeftWeight: number;
  borderStrokeWeightsIndependent: boolean;
  cornerSmoothing: number;
  blendMode: string;
  mask: boolean;
  frameMaskDisabled: boolean;
}

/** Text's scalar fields (TextFacet) */
export interface TextFacet {
  fontSize: number;
  lineHeight: { value: number; units: string };
  letterSpacing: { value: number; units: string };
  paragraphSpacing: number;
  paragraphIndent: number;
  textAlignHorizontal: string;
  textAlignVertical: string;
  textAutoResize: string;
  textTruncation: string;
  maxLines: number;
  textCase: string;
  textDecoration: string;
  autoRename: boolean;
}

type Into = Record<string, unknown>;

/** Decodes a geometry record at `a[o]` into `into` (an absent optional is deleted). */
export function decodeGeometry(a: Float64Array, o: number, into: Into): void {
  into["type"] = NodeType[a[o]] ?? "";
  into["visible"] = a[o + 1] !== 0;
  into["locked"] = a[o + 2] !== 0;
  into["opacity"] = a[o + 3];
  into["transform"] = { m00: a[o + 4], m01: a[o + 5], m02: a[o + 6], m10: a[o + 7], m11: a[o + 8], m12: a[o + 9] };
  into["size"] = { x: a[o + 10], y: a[o + 11] };
  into["cornerRadius"] = a[o + 12];
  into["rectangleCornerRadiiIndependent"] = a[o + 13] !== 0;
  into["rectangleTopLeftCornerRadius"] = a[o + 14];
  into["rectangleTopRightCornerRadius"] = a[o + 15];
  into["rectangleBottomRightCornerRadius"] = a[o + 16];
  into["rectangleBottomLeftCornerRadius"] = a[o + 17];
  into["horizontalConstraint"] = ConstraintType[a[o + 18]] ?? "";
  into["verticalConstraint"] = ConstraintType[a[o + 19]] ?? "";
  into["proportionsConstrained"] = a[o + 20] !== 0;
  into["stackChildPrimaryGrow"] = a[o + 21];
  into["stackChildAlignSelf"] = StackCounterAlign[a[o + 22]] ?? "";
  into["stackPositioning"] = StackPositioning[a[o + 23]] ?? "";
}

/** Decodes a shape record at `a[o]` into `into` (an absent optional is deleted). */
export function decodeShape(a: Float64Array, o: number, into: Into): void {
  into["arcData"] = { startingAngle: a[o], endingAngle: a[o + 1], innerRadius: a[o + 2] };
  into["count"] = a[o + 3];
  into["starInnerScale"] = a[o + 4];
}

/** Decodes a stack record at `a[o]` into `into` (an absent optional is deleted). */
export function decodeStack(a: Float64Array, o: number, into: Into): void {
  into["stackMode"] = StackMode[a[o]] ?? "";
  into["stackSpacing"] = a[o + 1];
  if (Number.isNaN(a[o + 2])) delete into["stackCounterSpacing"];
  else into["stackCounterSpacing"] = a[o + 2];
  into["stackHorizontalPadding"] = a[o + 3];
  into["stackVerticalPadding"] = a[o + 4];
  into["stackPaddingRight"] = a[o + 5];
  into["stackPaddingBottom"] = a[o + 6];
  into["stackPrimarySizing"] = StackSize[a[o + 7]] ?? "";
  into["stackCounterSizing"] = StackSize[a[o + 8]] ?? "";
  into["stackPrimaryAlignItems"] = StackJustify[a[o + 9]] ?? "";
  into["stackCounterAlignItems"] = StackAlign[a[o + 10]] ?? "";
  into["stackCounterAlignContent"] = StackCounterAlignContent[a[o + 11]] ?? "";
  into["stackWrap"] = StackWrap[a[o + 12]] ?? "";
  into["stackReverseZIndex"] = a[o + 13] !== 0;
  into["bordersTakeSpace"] = a[o + 14] !== 0;
  into["minSize"] = { value: { x: a[o + 15], y: a[o + 16] } };
  into["maxSize"] = { value: { x: a[o + 17], y: a[o + 18] } };
}

/** Decodes a stroke record at `a[o]` into `into` (an absent optional is deleted). */
export function decodeStroke(a: Float64Array, o: number, into: Into): void {
  into["strokeWeight"] = a[o];
  into["strokeAlign"] = StrokeAlign[a[o + 1]] ?? "";
  into["strokeCap"] = StrokeCap[a[o + 2]] ?? "";
  into["strokeJoin"] = StrokeJoin[a[o + 3]] ?? "";
  into["miterLimit"] = a[o + 4];
  into["borderTopWeight"] = a[o + 5];
  into["borderRightWeight"] = a[o + 6];
  into["borderBottomWeight"] = a[o + 7];
  into["borderLeftWeight"] = a[o + 8];
  into["borderStrokeWeightsIndependent"] = a[o + 9] !== 0;
  into["cornerSmoothing"] = a[o + 10];
  into["blendMode"] = BlendMode[a[o + 11]] ?? "";
  into["mask"] = a[o + 12] !== 0;
  into["frameMaskDisabled"] = a[o + 13] !== 0;
}

/** Decodes a text record at `a[o]` into `into` (an absent optional is deleted). */
export function decodeText(a: Float64Array, o: number, into: Into): void {
  into["fontSize"] = a[o];
  into["lineHeight"] = { value: a[o + 1], units: NumberUnits[a[o + 2]] ?? "" };
  into["letterSpacing"] = { value: a[o + 3], units: NumberUnits[a[o + 4]] ?? "" };
  into["paragraphSpacing"] = a[o + 5];
  into["paragraphIndent"] = a[o + 6];
  into["textAlignHorizontal"] = TextAlignHorizontal[a[o + 7]] ?? "";
  into["textAlignVertical"] = TextAlignVertical[a[o + 8]] ?? "";
  into["textAutoResize"] = TextAutoResize[a[o + 9]] ?? "";
  into["textTruncation"] = TextTruncation[a[o + 10]] ?? "";
  into["maxLines"] = a[o + 11];
  into["textCase"] = TextCase[a[o + 12]] ?? "";
  into["textDecoration"] = TextDecoration[a[o + 13]] ?? "";
  into["autoRename"] = a[o + 14] !== 0;
}

/** The decoders by facet. */
export const FACET_DECODERS: Readonly<Record<FacetName, (a: Float64Array, o: number, into: Into) => void>> = { geometry: decodeGeometry, shape: decodeShape, stack: decodeStack, stroke: decodeStroke, text: decodeText };
