/** The DS's own words: English, in Figma's wording (AGENTS.md). */
export const STRINGS = {
  mixed: "Mixed",
  search: "Search",
  clear: "Clear",
  close: "Close",
  noResults: "No results",
  untitled: "Untitled",
  home: "Home",
  newDesignFile: "New design file",
  collapse: "Collapse",
  expand: "Expand",
  lock: "Lock",
  unlock: "Unlock",
  show: "Show",
  hide: "Hide",
  rename: "Rename",
  dismiss: "Dismiss",
  loading: "Loading",
  unsaved: "Unsaved changes",
} as const;
