import { CHROME_COLORS, canvasChrome, canvasChromeMetrics, parseColor, staticVariables, surfaceBackground, themeVariables } from "./tokens";

/**
 * Pure renderers of the generated artefacts (contract §2.2): the tokens
 * stylesheet, the pre-paint boot script and the engine's palette header.
 * The tokens test re-renders tokens.css and fails when the committed file
 * differs; scripts/gen-tokens.ts (shell side) writes all three.
 */

export const LAYER_ORDER = "@layer reset, tokens, theme, base, ds, components, utilities, app;";

const block = (selector: string, vars: Record<string, string>, extra = "") =>
  `  ${selector} {\n${extra ? `    ${extra}\n` : ""}${Object.entries(vars).map(([k, v]) => `    ${k}: ${v};`).join("\n")}\n  }`;

/** tokens.css: static tokens on :root; light on :root and any [data-theme="light"] subtree; dark on [data-theme="dark"]. */
export function renderTokensCss(): string {
  return [
    "/* GENERATED by scripts/gen-tokens.ts from ds/tokens.ts (renderTokensCss) — do not edit */",
    LAYER_ORDER,
    "@layer tokens {",
    block(":root", staticVariables()),
    block(':root,\n  [data-theme="light"]', themeVariables("light"), "color-scheme: light;"),
    block('[data-theme="dark"]', themeVariables("dark"), "color-scheme: dark;"),
    "}",
    "",
  ].join("\n");
}

/** public/boot.js: data-theme, color-scheme and the surface's background before the first paint. */
export function renderBootJs(): string {
  const bg = (s: "app" | "tabbar" | "viewer") => JSON.stringify([surfaceBackground(s, "light"), surfaceBackground(s, "dark")]);
  return `// GENERATED by scripts/gen-tokens.ts from ds/tokens.ts (renderBootJs) — sets data-theme, color-scheme and background before the first paint
(function () {
  var d = document.documentElement, t = null;
  try { t = window.designer && window.designer.theme; } catch (e) { /* none */ }
  var pref = t ? t.preference : (function () { try { return localStorage.getItem("designer-theme") || "system"; } catch (e) { return "system"; } })();
  var dark = t ? t.resolved === "dark" : pref === "dark" || (pref !== "light" && matchMedia("(prefers-color-scheme: dark)").matches);
  var BG = { app: ${bg("app")}, tabbar: ${bg("tabbar")}, viewer: ${bg("viewer")} };
  d.setAttribute("data-theme", dark ? "dark" : "light");
  d.style.colorScheme = dark ? "dark" : "light";
  d.style.backgroundColor = (BG[d.getAttribute("data-surface")] || BG.app)[dark ? 1 : 0];
})();
`;
}

/**
 * The generated block of public/boot.js (between its "// <generated" and "// </generated>" lines): each
 * surface's background [light, dark] before the first paint (`surfaceBackground`). The rest of boot.js is
 * the shell's.
 */
export function renderBootSurfaces(indent = "  "): string {
  const bg = (s: "app" | "tabbar" | "viewer") => JSON.stringify([surfaceBackground(s, "light"), surfaceBackground(s, "dark")]).replace(/","/g, '", "');
  return [
    `${indent}// <generated by scripts/gen-tokens.ts from ds/tokens.ts — each surface's background [light, dark]; do not edit>`,
    `${indent}var SURFACE_BG = { app: ${bg("app")}, tabbar: ${bg("tabbar")}, viewer: ${bg("viewer")} };`,
    `${indent}// </generated>`,
    "",
  ].join("\n");
}

const f = (n: number) => {
  const s = Number(n.toFixed(6)).toString();
  return s.includes(".") ? `${s}f` : `${s}.0f`;
};

/** The engine's ChromePalette.generated.h (§2.2.3). */
export function renderChromeHeader(): string {
  const pascal = (s: string) => s[0].toUpperCase() + s.slice(1);
  const rows = (i: 0 | 1) =>
    CHROME_COLORS.map((name) => {
      const c = parseColor(canvasChrome[name][i]);
      if (!c) throw new Error(`Bad chrome colour ${name}`);
      return `  {${c.map(f).join(", ")}}, // ${name}`;
    }).join("\n");
  const m = canvasChromeMetrics;
  return `// GENERATED by scripts/gen-tokens.ts from ds/tokens.ts (renderChromeHeader) — do not edit
#pragma once
#include <cstddef>
#include <cstdint>
namespace ds {
enum class ChromeColor : uint8_t { ${CHROME_COLORS.map((n, i) => `${pascal(n)} = ${i}`).join(", ")}, Count };
inline constexpr float kChromeLight[size_t(ChromeColor::Count)][4] = {
${rows(0)}
};
inline constexpr float kChromeDark[size_t(ChromeColor::Count)][4] = {
${rows(1)}
};
struct ChromeMetrics { float selectionStroke, hoverStroke, handle, badgeHeight, badgePadX, badgeRadius, badgeGap, titleBaseline, rulerThickness, rulerTick, rulerFontSize; };
inline constexpr ChromeMetrics kChromeMetrics{ ${[m.selectionStroke, m.hoverStroke, m.handle, m.sizeBadge.height, m.sizeBadge.padX, m.sizeBadge.radius, m.sizeBadge.gap, m.titleBaseline, m.ruler.thickness, m.ruler.tick, m.ruler.fontSize].join(", ")} };
}
`;
}
